### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by kerat71** [Vadim-Kononov/ESP32_Electricity_Meter#2]
Hi, I get this error when compile on Arduino IDE 1.8.13 with all updated libraries:
Alternatives for interrupts.h: []e:\Arduino\libraries\ESPAsyncTCP\src\SyncClient.cpp:25:24: fatal error: interrupts.h: No such file or directory

ResolveLibrary(interrupts.h)
compilation terminated.
  -> candidates: []
Arduino core for ESP32 is 1.0.4
Can you please put me in the right direction to solve this? 
Regards,
Milen

**Comment by Vadim-Kononov** [comment]
Добрый день. Я не сталкивался с такой проблемой, и не смогу помочь. Но посмотрите здесь: https://github.com/me-no-dev/AsyncTCP/issues/81  Также мне кажется нестандартным путь к библиотекам e:\Arduino\libraries\ESPAsyncTCP\...
обычно e:\Program Files (x86)\Arduino\libraries... , но не уверен, что это может иметь значение в данном случае.

**Comment by kerat71** [comment]
Thank you for the answer! I use Arduino IDE from the FLProg installation and may be that is the problem, nevertheless I didn't have any issue until now. I will try with new installation of Arduino IDE.
